package io.music_assistant.client.ui.compose.common.providers

import co.touchlab.kermit.Logger
import io.music_assistant.client.utils.myJson
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.builtins.serializer
import musicassistantclient.composeapp.generated.resources.Res
import kotlin.coroutines.CoroutineContext

/**
 * Loads the official Material Design Icons name -> codepoint table once, from the slim
 * `files/mdi_codepoints.json` asset generated by the `generateMdiResources` Gradle task.
 *
 * Exposed as a Koin `single` so the (one-time) parse is shared process-wide; [MdiIcon]
 * collects [table] to resolve glyphs at render time. Stays empty until the load completes.
 */
class MdiCodepoints : CoroutineScope {
    override val coroutineContext: CoroutineContext = SupervisorJob() + Dispatchers.Default

    private val _table = MutableStateFlow<Map<String, Int>>(emptyMap())
    val table: StateFlow<Map<String, Int>> = _table.asStateFlow()

    init {
        launch {
            runCatching {
                val raw = Res.readBytes("files/mdi_codepoints.json").decodeToString()
                myJson.decodeFromString(
                    MapSerializer(String.serializer(), String.serializer()),
                    raw,
                ).mapValues { (_, hex) -> hex.toInt(RADIX) }
            }.onSuccess { parsed ->
                _table.update { parsed }
            }.onFailure { e ->
                Logger.e("Failed to load MDI codepoint table: ${e.message}")
            }
        }
    }
}

private const val RADIX = 16
